### ISSUE TITLE
Push final Homepage code into Homepage branch

### ISSUE THREAD

**Issue by dorothyle** [include-davis/bloom-and-vine#13]
Once all your code is in the appropriate branch, please close this issue so we know that you've completed the task. Make sure to pull from main as well.

For the Homepage branch, please have only the code for the homepage and move the services page, the navbar, and the footer to their corresponding branches.

**Comment by ryyu444** [comment]
Removed Navbar, Footer, & Services content. Pushed basically completed Desktop display.
